application: __APP_NAME__
version: 1
runtime: php
api_version: 1

handlers:
- url: /saksbehandling/
  static_files: saksbehandling/index.html
  upload: saksbehandling/index\.html

- url: /saksbehandling
  static_dir: saksbehandling

- url: /.*
  script: helloworld.php
